const Constants = {}

Constants.EVENT_SCROLL = 'EVENT_SCROLL'
Constants.EVENT_SCROLL_END = 'EVENT_SCROLL_END'
Constants.EVENT_RESIZE = 'EVENT_RESIZE'
Constants.EVENT_BREAKPOINT_CHANGE = 'EVENT_BREAKPOINT_CHANGE'

Constants.EVENT_APP_START = 'EVENT_APP_START'
Constants.EVENT_CHANGE_VIEW_START = 'EVENT_CHANGE_VIEW_START'
Constants.EVENT_CHANGE_VIEW_COMPLETE = 'EVENT_CHANGE_VIEW_COMPLETE'
Constants.EVENT_CHANGE_PARTIAL_VIEW = 'EVENT_CHANGE_PARTIAL_VIEW'

Constants.EVENT_UPDATE_SCROLL_ITEMS = 'EVENT_UPDATE_SCROLL_ITEMS'

Constants.EVENT_HASH_CHANGED = 'EVENT_HASH_CHANGED'
Constants.EVENT_ANCHOR_CHANGED = 'EVENT_ANCHOR_CHANGED'

Constants.EVENT_PAGE_LOAD_START = 'EVENT_PAGE_LOAD_START'
Constants.EVENT_PAGE_LOAD_PROGRESS = 'EVENT_PAGE_LOAD_PROGRESS'
Constants.EVENT_PAGE_LOAD_END = 'EVENT_PAGE_LOAD_END'
Constants.EVENT_PAGE_LOAD_ABORT = 'EVENT_PAGE_LOAD_ABORT'
Constants.EVENT_PAGE_LOAD_ERROR = 'EVENT_PAGE_LOAD_ERROR'

Constants.EVENT_SHOW_GLOBAL_LOADING = 'EVENT_SHOW_GLOBAL_LOADING'
Constants.EVENT_HIDE_GLOBAL_LOADING = 'EVENT_HIDE_GLOBAL_LOADING'

Constants.EVENT_GALLERY_MODAL_SHOW = 'EVENT_GALLERY_MODAL_SHOW'
Constants.EVENT_GALLERY_MODAL_HIDE = 'EVENT_GALLERY_MODAL_HIDE'

Constants.SCROLL_THROTTLE = 50
Constants.SCROLL_END_THROTTLE = 50
Constants.SCROLL_THRESHOLD = .15
Constants.SCROLL_SHOW_TIMEOUT = 300

Constants.RESIZE_DEBOUNCE = 250

Constants.SCROLL_ITEM_SELECTOR = 'data-scroll-item'
Constants.SCROLL_ITEM_SHOW = 'show'
Constants.SCROLL_ITEM_EVENT = 'data-scroll-item-event'

Constants.REQUEST_PAGE_MODEL = 'REQUEST_PAGE_MODEL'

export default Constants
